/**
 * This class is generated by jOOQ
 */
package net.catharos.societies.database.sql.layout;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Societies extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 586168681;

	/**
	 * The singleton instance of <code>societies</code>
	 */
	public static final Societies SOCIETIES = new Societies();

	/**
	 * No further instances allowed
	 */
	private Societies() {
		super("societies");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			net.catharos.societies.database.sql.layout.tables.Members.MEMBERS,
			net.catharos.societies.database.sql.layout.tables.MembersRanks.MEMBERS_RANKS,
			net.catharos.societies.database.sql.layout.tables.Ranks.RANKS,
			net.catharos.societies.database.sql.layout.tables.RanksSettings.RANKS_SETTINGS,
			net.catharos.societies.database.sql.layout.tables.Relations.RELATIONS,
			net.catharos.societies.database.sql.layout.tables.Societies.SOCIETIES,
			net.catharos.societies.database.sql.layout.tables.SocietiesRanks.SOCIETIES_RANKS,
			net.catharos.societies.database.sql.layout.tables.SocietiesSettings.SOCIETIES_SETTINGS);
	}
}
