/**
 * This class is generated by jOOQ
 */
package org.societies.database.sql.layout;

/**
 * Convenience access to all tables in societies
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table societies.cities
	 */
	public static final org.societies.database.sql.layout.tables.Cities CITIES = org.societies.database.sql.layout.tables.Cities.CITIES;

	/**
	 * The table societies.lands
	 */
	public static final org.societies.database.sql.layout.tables.Lands LANDS = org.societies.database.sql.layout.tables.Lands.LANDS;

	/**
	 * The table societies.members
	 */
	public static final org.societies.database.sql.layout.tables.Members MEMBERS = org.societies.database.sql.layout.tables.Members.MEMBERS;

	/**
	 * The table societies.members_ranks
	 */
	public static final org.societies.database.sql.layout.tables.MembersRanks MEMBERS_RANKS = org.societies.database.sql.layout.tables.MembersRanks.MEMBERS_RANKS;

	/**
	 * The table societies.member_settings
	 */
	public static final org.societies.database.sql.layout.tables.MemberSettings MEMBER_SETTINGS = org.societies.database.sql.layout.tables.MemberSettings.MEMBER_SETTINGS;

	/**
	 * The table societies.ranks
	 */
	public static final org.societies.database.sql.layout.tables.Ranks RANKS = org.societies.database.sql.layout.tables.Ranks.RANKS;

	/**
	 * The table societies.ranks_settings
	 */
	public static final org.societies.database.sql.layout.tables.RanksSettings RANKS_SETTINGS = org.societies.database.sql.layout.tables.RanksSettings.RANKS_SETTINGS;

	/**
	 * The table societies.relations
	 */
	public static final org.societies.database.sql.layout.tables.Relations RELATIONS = org.societies.database.sql.layout.tables.Relations.RELATIONS;

	/**
	 * The table societies.sieges
	 */
	public static final org.societies.database.sql.layout.tables.Sieges SIEGES = org.societies.database.sql.layout.tables.Sieges.SIEGES;

	/**
	 * The table societies.societies
	 */
	public static final org.societies.database.sql.layout.tables.Societies SOCIETIES = org.societies.database.sql.layout.tables.Societies.SOCIETIES;

	/**
	 * The table societies.societies_locks
	 */
	public static final org.societies.database.sql.layout.tables.SocietiesLocks SOCIETIES_LOCKS = org.societies.database.sql.layout.tables.SocietiesLocks.SOCIETIES_LOCKS;

	/**
	 * The table societies.societies_ranks
	 */
	public static final org.societies.database.sql.layout.tables.SocietiesRanks SOCIETIES_RANKS = org.societies.database.sql.layout.tables.SocietiesRanks.SOCIETIES_RANKS;

	/**
	 * The table societies.societies_settings
	 */
	public static final org.societies.database.sql.layout.tables.SocietiesSettings SOCIETIES_SETTINGS = org.societies.database.sql.layout.tables.SocietiesSettings.SOCIETIES_SETTINGS;
}
