/**
 * This class is generated by jOOQ
 */
package org.societies.database.sql.layout.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Lands extends org.jooq.impl.TableImpl<org.societies.database.sql.layout.tables.records.LandsRecord> {

	private static final long serialVersionUID = -253716766;

	/**
	 * The reference instance of <code>societies.lands</code>
	 */
	public static final org.societies.database.sql.layout.tables.Lands LANDS = new org.societies.database.sql.layout.tables.Lands();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.societies.database.sql.layout.tables.records.LandsRecord> getRecordType() {
		return org.societies.database.sql.layout.tables.records.LandsRecord.class;
	}

	/**
	 * The column <code>societies.lands.uuid</code>.
	 */
	public final org.jooq.TableField<org.societies.database.sql.layout.tables.records.LandsRecord, java.util.UUID> UUID = createField("uuid", org.jooq.impl.SQLDataType.VARBINARY.length(16).nullable(false), this, "", new org.societies.database.sql.UUIDConverter());

	/**
	 * The column <code>societies.lands.origin</code>.
	 */
	public final org.jooq.TableField<org.societies.database.sql.layout.tables.records.LandsRecord, java.util.UUID> ORIGIN = createField("origin", org.jooq.impl.SQLDataType.VARBINARY.length(16), this, "", new org.societies.database.sql.UUIDConverter());

	/**
	 * Create a <code>societies.lands</code> table reference
	 */
	public Lands() {
		this("lands", null);
	}

	/**
	 * Create an aliased <code>societies.lands</code> table reference
	 */
	public Lands(java.lang.String alias) {
		this(alias, org.societies.database.sql.layout.tables.Lands.LANDS);
	}

	private Lands(java.lang.String alias, org.jooq.Table<org.societies.database.sql.layout.tables.records.LandsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Lands(java.lang.String alias, org.jooq.Table<org.societies.database.sql.layout.tables.records.LandsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.societies.database.sql.layout.Societies.SOCIETIES, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.societies.database.sql.layout.tables.records.LandsRecord> getPrimaryKey() {
		return org.societies.database.sql.layout.Keys.KEY_LANDS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.societies.database.sql.layout.tables.records.LandsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.societies.database.sql.layout.tables.records.LandsRecord>>asList(org.societies.database.sql.layout.Keys.KEY_LANDS_PRIMARY, org.societies.database.sql.layout.Keys.KEY_LANDS_IDLANDS_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.societies.database.sql.layout.tables.records.LandsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.societies.database.sql.layout.tables.records.LandsRecord, ?>>asList(org.societies.database.sql.layout.Keys.FK_LANDS_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.societies.database.sql.layout.tables.Lands as(java.lang.String alias) {
		return new org.societies.database.sql.layout.tables.Lands(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.societies.database.sql.layout.tables.Lands rename(java.lang.String name) {
		return new org.societies.database.sql.layout.tables.Lands(name, null);
	}
}
