/**
 * This class is generated by jOOQ
 */
package org.societies.database.sql.layout.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Members extends org.jooq.impl.TableImpl<org.societies.database.sql.layout.tables.records.MembersRecord> {

	private static final long serialVersionUID = 1851287759;

	/**
	 * The reference instance of <code>societies.members</code>
	 */
	public static final org.societies.database.sql.layout.tables.Members MEMBERS = new org.societies.database.sql.layout.tables.Members();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.societies.database.sql.layout.tables.records.MembersRecord> getRecordType() {
		return org.societies.database.sql.layout.tables.records.MembersRecord.class;
	}

	/**
	 * The column <code>societies.members.uuid</code>.
	 */
	public final org.jooq.TableField<org.societies.database.sql.layout.tables.records.MembersRecord, java.util.UUID> UUID = createField("uuid", org.jooq.impl.SQLDataType.VARBINARY.length(16).nullable(false), this, "", new org.societies.database.sql.UUIDConverter());

	/**
	 * The column <code>societies.members.created</code>.
	 */
	public final org.jooq.TableField<org.societies.database.sql.layout.tables.records.MembersRecord, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * The column <code>societies.members.society</code>.
	 */
	public final org.jooq.TableField<org.societies.database.sql.layout.tables.records.MembersRecord, java.util.UUID> SOCIETY = createField("society", org.jooq.impl.SQLDataType.VARBINARY.length(16), this, "", new org.societies.database.sql.UUIDConverter());

	/**
	 * The column <code>societies.members.lastActive</code>.
	 */
	public final org.jooq.TableField<org.societies.database.sql.layout.tables.records.MembersRecord, java.sql.Timestamp> LASTACTIVE = createField("lastActive", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * Create a <code>societies.members</code> table reference
	 */
	public Members() {
		this("members", null);
	}

	/**
	 * Create an aliased <code>societies.members</code> table reference
	 */
	public Members(java.lang.String alias) {
		this(alias, org.societies.database.sql.layout.tables.Members.MEMBERS);
	}

	private Members(java.lang.String alias, org.jooq.Table<org.societies.database.sql.layout.tables.records.MembersRecord> aliased) {
		this(alias, aliased, null);
	}

	private Members(java.lang.String alias, org.jooq.Table<org.societies.database.sql.layout.tables.records.MembersRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.societies.database.sql.layout.Societies.SOCIETIES, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.societies.database.sql.layout.tables.records.MembersRecord> getPrimaryKey() {
		return org.societies.database.sql.layout.Keys.KEY_MEMBERS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.societies.database.sql.layout.tables.records.MembersRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.societies.database.sql.layout.tables.records.MembersRecord>>asList(org.societies.database.sql.layout.Keys.KEY_MEMBERS_PRIMARY, org.societies.database.sql.layout.Keys.KEY_MEMBERS_UUID_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.societies.database.sql.layout.tables.records.MembersRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.societies.database.sql.layout.tables.records.MembersRecord, ?>>asList(org.societies.database.sql.layout.Keys.FK_MEMBERS_SOCIETIES1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.societies.database.sql.layout.tables.Members as(java.lang.String alias) {
		return new org.societies.database.sql.layout.tables.Members(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.societies.database.sql.layout.tables.Members rename(java.lang.String name) {
		return new org.societies.database.sql.layout.tables.Members(name, null);
	}
}
