/**
 * This class is generated by jOOQ
 */
package org.societies.database.sql.layout.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ranks extends org.jooq.impl.TableImpl<org.societies.database.sql.layout.tables.records.RanksRecord> {

	private static final long serialVersionUID = 1937441937;

	/**
	 * The singleton instance of <code>societies.ranks</code>
	 */
	public static final org.societies.database.sql.layout.tables.Ranks RANKS = new org.societies.database.sql.layout.tables.Ranks();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.societies.database.sql.layout.tables.records.RanksRecord> getRecordType() {
		return org.societies.database.sql.layout.tables.records.RanksRecord.class;
	}

	/**
	 * The column <code>societies.ranks.uuid</code>.
	 */
	public final org.jooq.TableField<org.societies.database.sql.layout.tables.records.RanksRecord, byte[]> UUID = createField("uuid", org.jooq.impl.SQLDataType.VARBINARY.length(16).nullable(false), this, "");

	/**
	 * The column <code>societies.ranks.name</code>.
	 */
	public final org.jooq.TableField<org.societies.database.sql.layout.tables.records.RanksRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>societies.ranks.priority</code>.
	 */
	public final org.jooq.TableField<org.societies.database.sql.layout.tables.records.RanksRecord, java.lang.Short> PRIORITY = createField("priority", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * Create a <code>societies.ranks</code> table reference
	 */
	public Ranks() {
		this("ranks", null);
	}

	/**
	 * Create an aliased <code>societies.ranks</code> table reference
	 */
	public Ranks(java.lang.String alias) {
		this(alias, org.societies.database.sql.layout.tables.Ranks.RANKS);
	}

	private Ranks(java.lang.String alias, org.jooq.Table<org.societies.database.sql.layout.tables.records.RanksRecord> aliased) {
		this(alias, aliased, null);
	}

	private Ranks(java.lang.String alias, org.jooq.Table<org.societies.database.sql.layout.tables.records.RanksRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.societies.database.sql.layout.Societies.SOCIETIES, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.societies.database.sql.layout.tables.records.RanksRecord> getPrimaryKey() {
		return org.societies.database.sql.layout.Keys.KEY_RANKS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.societies.database.sql.layout.tables.records.RanksRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.societies.database.sql.layout.tables.records.RanksRecord>>asList(org.societies.database.sql.layout.Keys.KEY_RANKS_PRIMARY, org.societies.database.sql.layout.Keys.KEY_RANKS_NAME_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.societies.database.sql.layout.tables.Ranks as(java.lang.String alias) {
		return new org.societies.database.sql.layout.tables.Ranks(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.societies.database.sql.layout.tables.Ranks rename(java.lang.String name) {
		return new org.societies.database.sql.layout.tables.Ranks(name, null);
	}
}
