/**
 * This class is generated by jOOQ
 */
package org.societies.database.sql.layout.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value = {"http://www.jooq.org", "3.4.4"},
        comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Relations extends org.jooq.impl.TableImpl<org.societies.database.sql.layout.tables.records.RelationsRecord> {

    private static final long serialVersionUID = 1495485824;

    /**
     * The singleton instance of <code>societies.relations</code>
     */
    public static final org.societies.database.sql.layout.tables.Relations RELATIONS = new org.societies.database.sql.layout.tables.Relations();

    /**
     * The class holding records for this type
     */
    @Override
    public java.lang.Class<org.societies.database.sql.layout.tables.records.RelationsRecord> getRecordType() {
        return org.societies.database.sql.layout.tables.records.RelationsRecord.class;
    }

    /**
     * The column <code>societies.relations.society</code>.
     */
    public final org.jooq.TableField<org.societies.database.sql.layout.tables.records.RelationsRecord, byte[]> SOCIETY = createField("society", org.jooq.impl.SQLDataType.VARBINARY
            .length(16).nullable(false), this, "");

    /**
     * The column <code>societies.relations.society2</code>.
     */
    public final org.jooq.TableField<org.societies.database.sql.layout.tables.records.RelationsRecord, byte[]> SOCIETY2 = createField("society2", org.jooq.impl.SQLDataType.VARBINARY
            .length(16).nullable(false), this, "");

    /**
     * The column <code>societies.relations.type</code>.
     */
    public final org.jooq.TableField<org.societies.database.sql.layout.tables.records.RelationsRecord, java.lang.Short> TYPE = createField("type", org.jooq.impl.SQLDataType.SMALLINT, this, "");

    /**
     * Create a <code>societies.relations</code> table reference
     */
    public Relations() {
        this("relations", null);
    }

    /**
     * Create an aliased <code>societies.relations</code> table reference
     */
    public Relations(java.lang.String alias) {
        this(alias, org.societies.database.sql.layout.tables.Relations.RELATIONS);
    }

    private Relations(java.lang.String alias, org.jooq.Table<org.societies.database.sql.layout.tables.records.RelationsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Relations(java.lang.String alias, org.jooq.Table<org.societies.database.sql.layout.tables.records.RelationsRecord> aliased, org.jooq.Field<?>[] parameters) {
        super(alias, org.societies.database.sql.layout.Societies.SOCIETIES, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.UniqueKey<org.societies.database.sql.layout.tables.records.RelationsRecord> getPrimaryKey() {
        return org.societies.database.sql.layout.Keys.KEY_RELATIONS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.util.List<org.jooq.UniqueKey<org.societies.database.sql.layout.tables.records.RelationsRecord>> getKeys() {
        return java.util.Arrays
                .<org.jooq.UniqueKey<org.societies.database.sql.layout.tables.records.RelationsRecord>>asList(org.societies.database.sql.layout.Keys.KEY_RELATIONS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.util.List<org.jooq.ForeignKey<org.societies.database.sql.layout.tables.records.RelationsRecord, ?>> getReferences() {
        return java.util.Arrays
                .<org.jooq.ForeignKey<org.societies.database.sql.layout.tables.records.RelationsRecord, ?>>asList(org.societies.database.sql.layout.Keys.FK_SOCIETIES_HAS_SOCIETIES_SOCIETIES1, org.societies.database.sql.layout.Keys.FK_SOCIETIES_HAS_SOCIETIES_SOCIETIES2);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.societies.database.sql.layout.tables.Relations as(java.lang.String alias) {
        return new org.societies.database.sql.layout.tables.Relations(alias, this);
    }

    /**
     * Rename this table
     */
    public org.societies.database.sql.layout.tables.Relations rename(java.lang.String name) {
        return new org.societies.database.sql.layout.tables.Relations(name, null);
    }
}
