/**
 * This class is generated by jOOQ
 */
package org.societies.database.sql.layout.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sieges extends org.jooq.impl.TableImpl<org.societies.database.sql.layout.tables.records.SiegesRecord> {

	private static final long serialVersionUID = -1650943445;

	/**
	 * The singleton instance of <code>societies.sieges</code>
	 */
	public static final org.societies.database.sql.layout.tables.Sieges SIEGES = new org.societies.database.sql.layout.tables.Sieges();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.societies.database.sql.layout.tables.records.SiegesRecord> getRecordType() {
		return org.societies.database.sql.layout.tables.records.SiegesRecord.class;
	}

	/**
	 * The column <code>societies.sieges.uuid</code>.
	 */
	public final org.jooq.TableField<org.societies.database.sql.layout.tables.records.SiegesRecord, byte[]> UUID = createField("uuid", org.jooq.impl.SQLDataType.VARBINARY.length(16).nullable(false), this, "");

	/**
	 * The column <code>societies.sieges.society</code>.
	 */
	public final org.jooq.TableField<org.societies.database.sql.layout.tables.records.SiegesRecord, byte[]> SOCIETY = createField("society", org.jooq.impl.SQLDataType.VARBINARY.length(16).nullable(false), this, "");

	/**
	 * The column <code>societies.sieges.city</code>.
	 */
	public final org.jooq.TableField<org.societies.database.sql.layout.tables.records.SiegesRecord, byte[]> CITY = createField("city", org.jooq.impl.SQLDataType.VARBINARY.length(16).nullable(false), this, "");

	/**
	 * The column <code>societies.sieges.x</code>.
	 */
	public final org.jooq.TableField<org.societies.database.sql.layout.tables.records.SiegesRecord, java.lang.Short> X = createField("x", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>societies.sieges.y</code>.
	 */
	public final org.jooq.TableField<org.societies.database.sql.layout.tables.records.SiegesRecord, java.lang.Short> Y = createField("y", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>societies.sieges.z</code>.
	 */
	public final org.jooq.TableField<org.societies.database.sql.layout.tables.records.SiegesRecord, java.lang.Short> Z = createField("z", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>societies.sieges.created</code>.
	 */
	public final org.jooq.TableField<org.societies.database.sql.layout.tables.records.SiegesRecord, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * The column <code>societies.sieges.wager</code>.
	 */
	public final org.jooq.TableField<org.societies.database.sql.layout.tables.records.SiegesRecord, byte[]> WAGER = createField("wager", org.jooq.impl.SQLDataType.VARBINARY.length(16), this, "");

	/**
	 * Create a <code>societies.sieges</code> table reference
	 */
	public Sieges() {
		this("sieges", null);
	}

	/**
	 * Create an aliased <code>societies.sieges</code> table reference
	 */
	public Sieges(java.lang.String alias) {
		this(alias, org.societies.database.sql.layout.tables.Sieges.SIEGES);
	}

	private Sieges(java.lang.String alias, org.jooq.Table<org.societies.database.sql.layout.tables.records.SiegesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Sieges(java.lang.String alias, org.jooq.Table<org.societies.database.sql.layout.tables.records.SiegesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.societies.database.sql.layout.Societies.SOCIETIES, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.societies.database.sql.layout.tables.records.SiegesRecord> getPrimaryKey() {
		return org.societies.database.sql.layout.Keys.KEY_SIEGES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.societies.database.sql.layout.tables.records.SiegesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.societies.database.sql.layout.tables.records.SiegesRecord>>asList(org.societies.database.sql.layout.Keys.KEY_SIEGES_PRIMARY, org.societies.database.sql.layout.Keys.KEY_SIEGES_UUID_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.societies.database.sql.layout.tables.records.SiegesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.societies.database.sql.layout.tables.records.SiegesRecord, ?>>asList(org.societies.database.sql.layout.Keys.FK_SIEGES_1, org.societies.database.sql.layout.Keys.FK_SIEGES_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.societies.database.sql.layout.tables.Sieges as(java.lang.String alias) {
		return new org.societies.database.sql.layout.tables.Sieges(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.societies.database.sql.layout.tables.Sieges rename(java.lang.String name) {
		return new org.societies.database.sql.layout.tables.Sieges(name, null);
	}
}
