/**
 * This class is generated by jOOQ
 */
package org.societies.database.sql.layout.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SocietiesRanks extends org.jooq.impl.TableImpl<org.societies.database.sql.layout.tables.records.SocietiesRanksRecord> {

	private static final long serialVersionUID = -1854803899;

	/**
	 * The reference instance of <code>societies.societies_ranks</code>
	 */
	public static final org.societies.database.sql.layout.tables.SocietiesRanks SOCIETIES_RANKS = new org.societies.database.sql.layout.tables.SocietiesRanks();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.societies.database.sql.layout.tables.records.SocietiesRanksRecord> getRecordType() {
		return org.societies.database.sql.layout.tables.records.SocietiesRanksRecord.class;
	}

	/**
	 * The column <code>societies.societies_ranks.society</code>.
	 */
	public final org.jooq.TableField<org.societies.database.sql.layout.tables.records.SocietiesRanksRecord, java.util.UUID> SOCIETY = createField("society", org.jooq.impl.SQLDataType.VARBINARY.length(16).nullable(false), this, "", new org.societies.database.sql.UUIDConverter());

	/**
	 * The column <code>societies.societies_ranks.rank</code>.
	 */
	public final org.jooq.TableField<org.societies.database.sql.layout.tables.records.SocietiesRanksRecord, java.util.UUID> RANK = createField("rank", org.jooq.impl.SQLDataType.VARBINARY.length(16).nullable(false), this, "", new org.societies.database.sql.UUIDConverter());

	/**
	 * Create a <code>societies.societies_ranks</code> table reference
	 */
	public SocietiesRanks() {
		this("societies_ranks", null);
	}

	/**
	 * Create an aliased <code>societies.societies_ranks</code> table reference
	 */
	public SocietiesRanks(java.lang.String alias) {
		this(alias, org.societies.database.sql.layout.tables.SocietiesRanks.SOCIETIES_RANKS);
	}

	private SocietiesRanks(java.lang.String alias, org.jooq.Table<org.societies.database.sql.layout.tables.records.SocietiesRanksRecord> aliased) {
		this(alias, aliased, null);
	}

	private SocietiesRanks(java.lang.String alias, org.jooq.Table<org.societies.database.sql.layout.tables.records.SocietiesRanksRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.societies.database.sql.layout.Societies.SOCIETIES, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.societies.database.sql.layout.tables.records.SocietiesRanksRecord> getPrimaryKey() {
		return org.societies.database.sql.layout.Keys.KEY_SOCIETIES_RANKS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.societies.database.sql.layout.tables.records.SocietiesRanksRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.societies.database.sql.layout.tables.records.SocietiesRanksRecord>>asList(org.societies.database.sql.layout.Keys.KEY_SOCIETIES_RANKS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<org.societies.database.sql.layout.tables.records.SocietiesRanksRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<org.societies.database.sql.layout.tables.records.SocietiesRanksRecord, ?>>asList(org.societies.database.sql.layout.Keys.FK_SOCIETIES_HAS_RANKS_SOCIETIES2, org.societies.database.sql.layout.Keys.FK_SOCIETIES_HAS_RANKS_RANKS2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.societies.database.sql.layout.tables.SocietiesRanks as(java.lang.String alias) {
		return new org.societies.database.sql.layout.tables.SocietiesRanks(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.societies.database.sql.layout.tables.SocietiesRanks rename(java.lang.String name) {
		return new org.societies.database.sql.layout.tables.SocietiesRanks(name, null);
	}
}
