/**
 * This class is generated by jOOQ
 */
package net.catharos.societies.database.sql.layout.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MembersRanks extends org.jooq.impl.TableImpl<net.catharos.societies.database.sql.layout.tables.records.MembersRanksRecord> {

	private static final long serialVersionUID = -628828855;

	/**
	 * The singleton instance of <code>societies.members_ranks</code>
	 */
	public static final net.catharos.societies.database.sql.layout.tables.MembersRanks MEMBERS_RANKS = new net.catharos.societies.database.sql.layout.tables.MembersRanks();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.catharos.societies.database.sql.layout.tables.records.MembersRanksRecord> getRecordType() {
		return net.catharos.societies.database.sql.layout.tables.records.MembersRanksRecord.class;
	}

	/**
	 * The column <code>societies.members_ranks.member</code>.
	 */
	public final org.jooq.TableField<net.catharos.societies.database.sql.layout.tables.records.MembersRanksRecord, byte[]> MEMBER = createField("member", org.jooq.impl.SQLDataType.VARBINARY.length(16).nullable(false), this, "");

	/**
	 * The column <code>societies.members_ranks.rank</code>.
	 */
	public final org.jooq.TableField<net.catharos.societies.database.sql.layout.tables.records.MembersRanksRecord, byte[]> RANK = createField("rank", org.jooq.impl.SQLDataType.VARBINARY.length(16).nullable(false), this, "");

	/**
	 * Create a <code>societies.members_ranks</code> table reference
	 */
	public MembersRanks() {
		this("members_ranks", null);
	}

	/**
	 * Create an aliased <code>societies.members_ranks</code> table reference
	 */
	public MembersRanks(java.lang.String alias) {
		this(alias, net.catharos.societies.database.sql.layout.tables.MembersRanks.MEMBERS_RANKS);
	}

	private MembersRanks(java.lang.String alias, org.jooq.Table<net.catharos.societies.database.sql.layout.tables.records.MembersRanksRecord> aliased) {
		this(alias, aliased, null);
	}

	private MembersRanks(java.lang.String alias, org.jooq.Table<net.catharos.societies.database.sql.layout.tables.records.MembersRanksRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, net.catharos.societies.database.sql.layout.Societies.SOCIETIES, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<net.catharos.societies.database.sql.layout.tables.records.MembersRanksRecord> getPrimaryKey() {
		return net.catharos.societies.database.sql.layout.Keys.KEY_MEMBERS_RANKS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<net.catharos.societies.database.sql.layout.tables.records.MembersRanksRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.catharos.societies.database.sql.layout.tables.records.MembersRanksRecord>>asList(net.catharos.societies.database.sql.layout.Keys.KEY_MEMBERS_RANKS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<net.catharos.societies.database.sql.layout.tables.records.MembersRanksRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<net.catharos.societies.database.sql.layout.tables.records.MembersRanksRecord, ?>>asList(net.catharos.societies.database.sql.layout.Keys.FK_MEMBERS_HAS_RANKS_MEMBERS1, net.catharos.societies.database.sql.layout.Keys.FK_MEMBERS_HAS_RANKS_RANKS1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public net.catharos.societies.database.sql.layout.tables.MembersRanks as(java.lang.String alias) {
		return new net.catharos.societies.database.sql.layout.tables.MembersRanks(alias, this);
	}

	/**
	 * Rename this table
	 */
	public net.catharos.societies.database.sql.layout.tables.MembersRanks rename(java.lang.String name) {
		return new net.catharos.societies.database.sql.layout.tables.MembersRanks(name, null);
	}
}
