/**
 * This class is generated by jOOQ
 */
package net.catharos.societies.database.layout.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Members extends org.jooq.impl.TableImpl<net.catharos.societies.database.layout.tables.records.MembersRecord> {

	private static final long serialVersionUID = 1112444329;

	/**
	 * The singleton instance of <code>societies.members</code>
	 */
	public static final net.catharos.societies.database.layout.tables.Members MEMBERS = new net.catharos.societies.database.layout.tables.Members();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.catharos.societies.database.layout.tables.records.MembersRecord> getRecordType() {
		return net.catharos.societies.database.layout.tables.records.MembersRecord.class;
	}

	/**
	 * The column <code>societies.members.uuid</code>. 
	 */
	public final org.jooq.TableField<net.catharos.societies.database.layout.tables.records.MembersRecord, byte[]> UUID = createField("uuid", org.jooq.impl.SQLDataType.VARBINARY.length(16).nullable(false), this);

	/**
	 * The column <code>societies.members.created</code>. 
	 */
	public final org.jooq.TableField<net.catharos.societies.database.layout.tables.records.MembersRecord, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this);

	/**
	 * The column <code>societies.members.state</code>. 
	 */
	public final org.jooq.TableField<net.catharos.societies.database.layout.tables.records.MembersRecord, java.lang.Short> STATE = createField("state", org.jooq.impl.SQLDataType.SMALLINT, this);

	/**
	 * Create a <code>societies.members</code> table reference
	 */
	public Members() {
		super("members", net.catharos.societies.database.layout.Societies.SOCIETIES);
	}

	/**
	 * Create an aliased <code>societies.members</code> table reference
	 */
	public Members(java.lang.String alias) {
		super(alias, net.catharos.societies.database.layout.Societies.SOCIETIES, net.catharos.societies.database.layout.tables.Members.MEMBERS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<net.catharos.societies.database.layout.tables.records.MembersRecord> getPrimaryKey() {
		return net.catharos.societies.database.layout.Keys.KEY_MEMBERS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<net.catharos.societies.database.layout.tables.records.MembersRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.catharos.societies.database.layout.tables.records.MembersRecord>>asList(net.catharos.societies.database.layout.Keys.KEY_MEMBERS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public net.catharos.societies.database.layout.tables.Members as(java.lang.String alias) {
		return new net.catharos.societies.database.layout.tables.Members(alias);
	}
}
