/**
 * This class is generated by jOOQ
 */
package net.catharos.societies.database.layout.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Permissions extends org.jooq.impl.TableImpl<net.catharos.societies.database.layout.tables.records.PermissionsRecord> {

	private static final long serialVersionUID = 1872164887;

	/**
	 * The singleton instance of <code>societies.permissions</code>
	 */
	public static final net.catharos.societies.database.layout.tables.Permissions PERMISSIONS = new net.catharos.societies.database.layout.tables.Permissions();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.catharos.societies.database.layout.tables.records.PermissionsRecord> getRecordType() {
		return net.catharos.societies.database.layout.tables.records.PermissionsRecord.class;
	}

	/**
	 * The column <code>societies.permissions.uuid</code>. 
	 */
	public final org.jooq.TableField<net.catharos.societies.database.layout.tables.records.PermissionsRecord, byte[]> UUID = createField("uuid", org.jooq.impl.SQLDataType.VARBINARY.length(16).nullable(false), this);

	/**
	 * Create a <code>societies.permissions</code> table reference
	 */
	public Permissions() {
		super("permissions", net.catharos.societies.database.layout.Societies.SOCIETIES);
	}

	/**
	 * Create an aliased <code>societies.permissions</code> table reference
	 */
	public Permissions(java.lang.String alias) {
		super(alias, net.catharos.societies.database.layout.Societies.SOCIETIES, net.catharos.societies.database.layout.tables.Permissions.PERMISSIONS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<net.catharos.societies.database.layout.tables.records.PermissionsRecord> getPrimaryKey() {
		return net.catharos.societies.database.layout.Keys.KEY_PERMISSIONS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<net.catharos.societies.database.layout.tables.records.PermissionsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.catharos.societies.database.layout.tables.records.PermissionsRecord>>asList(net.catharos.societies.database.layout.Keys.KEY_PERMISSIONS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public net.catharos.societies.database.layout.tables.Permissions as(java.lang.String alias) {
		return new net.catharos.societies.database.layout.tables.Permissions(alias);
	}
}
