/**
 * This class is generated by jOOQ
 */
package net.catharos.societies.database.layout.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RanksPermissions extends org.jooq.impl.TableImpl<net.catharos.societies.database.layout.tables.records.RanksPermissionsRecord> {

	private static final long serialVersionUID = -946120649;

	/**
	 * The singleton instance of <code>societies.ranks_permissions</code>
	 */
	public static final net.catharos.societies.database.layout.tables.RanksPermissions RANKS_PERMISSIONS = new net.catharos.societies.database.layout.tables.RanksPermissions();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.catharos.societies.database.layout.tables.records.RanksPermissionsRecord> getRecordType() {
		return net.catharos.societies.database.layout.tables.records.RanksPermissionsRecord.class;
	}

	/**
	 * The column <code>societies.ranks_permissions.rank</code>. 
	 */
	public final org.jooq.TableField<net.catharos.societies.database.layout.tables.records.RanksPermissionsRecord, byte[]> RANK = createField("rank", org.jooq.impl.SQLDataType.VARBINARY.length(16).nullable(false), this);

	/**
	 * The column <code>societies.ranks_permissions.permission</code>. 
	 */
	public final org.jooq.TableField<net.catharos.societies.database.layout.tables.records.RanksPermissionsRecord, java.lang.Integer> PERMISSION = createField("permission", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * Create a <code>societies.ranks_permissions</code> table reference
	 */
	public RanksPermissions() {
		super("ranks_permissions", net.catharos.societies.database.layout.Societies.SOCIETIES);
	}

	/**
	 * Create an aliased <code>societies.ranks_permissions</code> table reference
	 */
	public RanksPermissions(java.lang.String alias) {
		super(alias, net.catharos.societies.database.layout.Societies.SOCIETIES, net.catharos.societies.database.layout.tables.RanksPermissions.RANKS_PERMISSIONS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<net.catharos.societies.database.layout.tables.records.RanksPermissionsRecord> getPrimaryKey() {
		return net.catharos.societies.database.layout.Keys.KEY_RANKS_PERMISSIONS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<net.catharos.societies.database.layout.tables.records.RanksPermissionsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.catharos.societies.database.layout.tables.records.RanksPermissionsRecord>>asList(net.catharos.societies.database.layout.Keys.KEY_RANKS_PERMISSIONS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<net.catharos.societies.database.layout.tables.records.RanksPermissionsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<net.catharos.societies.database.layout.tables.records.RanksPermissionsRecord, ?>>asList(net.catharos.societies.database.layout.Keys.FK_RANKS_HAS_PERMISSIONS_RANKS1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public net.catharos.societies.database.layout.tables.RanksPermissions as(java.lang.String alias) {
		return new net.catharos.societies.database.layout.tables.RanksPermissions(alias);
	}
}
