/**
 * This class is generated by jOOQ
 */
package net.catharos.societies.database.layout.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SocietiesRanks extends org.jooq.impl.TableImpl<net.catharos.societies.database.layout.tables.records.SocietiesRanksRecord> {

	private static final long serialVersionUID = -422142706;

	/**
	 * The singleton instance of <code>societies.societies_ranks</code>
	 */
	public static final net.catharos.societies.database.layout.tables.SocietiesRanks SOCIETIES_RANKS = new net.catharos.societies.database.layout.tables.SocietiesRanks();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.catharos.societies.database.layout.tables.records.SocietiesRanksRecord> getRecordType() {
		return net.catharos.societies.database.layout.tables.records.SocietiesRanksRecord.class;
	}

	/**
	 * The column <code>societies.societies_ranks.society</code>. 
	 */
	public final org.jooq.TableField<net.catharos.societies.database.layout.tables.records.SocietiesRanksRecord, byte[]> SOCIETY = createField("society", org.jooq.impl.SQLDataType.VARBINARY.length(16).nullable(false), this);

	/**
	 * The column <code>societies.societies_ranks.rank</code>. 
	 */
	public final org.jooq.TableField<net.catharos.societies.database.layout.tables.records.SocietiesRanksRecord, byte[]> RANK = createField("rank", org.jooq.impl.SQLDataType.VARBINARY.length(16).nullable(false), this);

	/**
	 * Create a <code>societies.societies_ranks</code> table reference
	 */
	public SocietiesRanks() {
		super("societies_ranks", net.catharos.societies.database.layout.Societies.SOCIETIES);
	}

	/**
	 * Create an aliased <code>societies.societies_ranks</code> table reference
	 */
	public SocietiesRanks(java.lang.String alias) {
		super(alias, net.catharos.societies.database.layout.Societies.SOCIETIES, net.catharos.societies.database.layout.tables.SocietiesRanks.SOCIETIES_RANKS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<net.catharos.societies.database.layout.tables.records.SocietiesRanksRecord> getPrimaryKey() {
		return net.catharos.societies.database.layout.Keys.KEY_SOCIETIES_RANKS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<net.catharos.societies.database.layout.tables.records.SocietiesRanksRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.catharos.societies.database.layout.tables.records.SocietiesRanksRecord>>asList(net.catharos.societies.database.layout.Keys.KEY_SOCIETIES_RANKS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<net.catharos.societies.database.layout.tables.records.SocietiesRanksRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<net.catharos.societies.database.layout.tables.records.SocietiesRanksRecord, ?>>asList(net.catharos.societies.database.layout.Keys.FK_SOCIETIES_HAS_RANKS_SOCIETIES2, net.catharos.societies.database.layout.Keys.FK_SOCIETIES_HAS_RANKS_RANKS2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public net.catharos.societies.database.layout.tables.SocietiesRanks as(java.lang.String alias) {
		return new net.catharos.societies.database.layout.tables.SocietiesRanks(alias);
	}
}
