/**
 * This class is generated by jOOQ
 */
package net.catharos.societies.database.layout.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SocietiesMembers extends org.jooq.impl.TableImpl<net.catharos.societies.database.layout.tables.records.SocietiesMembersRecord> {

	private static final long serialVersionUID = 1610404655;

	/**
	 * The singleton instance of <code>societies.societies_members</code>
	 */
	public static final net.catharos.societies.database.layout.tables.SocietiesMembers SOCIETIES_MEMBERS = new net.catharos.societies.database.layout.tables.SocietiesMembers();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<net.catharos.societies.database.layout.tables.records.SocietiesMembersRecord> getRecordType() {
		return net.catharos.societies.database.layout.tables.records.SocietiesMembersRecord.class;
	}

	/**
	 * The column <code>societies.societies_members.society</code>.
	 */
	public final org.jooq.TableField<net.catharos.societies.database.layout.tables.records.SocietiesMembersRecord, byte[]> SOCIETY = createField("society", org.jooq.impl.SQLDataType.VARBINARY.length(16).nullable(false), this, "");

	/**
	 * The column <code>societies.societies_members.member</code>.
	 */
	public final org.jooq.TableField<net.catharos.societies.database.layout.tables.records.SocietiesMembersRecord, byte[]> MEMBER = createField("member", org.jooq.impl.SQLDataType.VARBINARY.length(16).nullable(false), this, "");

	/**
	 * Create a <code>societies.societies_members</code> table reference
	 */
	public SocietiesMembers() {
		this("societies_members", null);
	}

	/**
	 * Create an aliased <code>societies.societies_members</code> table reference
	 */
	public SocietiesMembers(java.lang.String alias) {
		this(alias, net.catharos.societies.database.layout.tables.SocietiesMembers.SOCIETIES_MEMBERS);
	}

	private SocietiesMembers(java.lang.String alias, org.jooq.Table<net.catharos.societies.database.layout.tables.records.SocietiesMembersRecord> aliased) {
		this(alias, aliased, null);
	}

	private SocietiesMembers(java.lang.String alias, org.jooq.Table<net.catharos.societies.database.layout.tables.records.SocietiesMembersRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, net.catharos.societies.database.layout.Societies.SOCIETIES, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<net.catharos.societies.database.layout.tables.records.SocietiesMembersRecord> getPrimaryKey() {
		return net.catharos.societies.database.layout.Keys.KEY_SOCIETIES_MEMBERS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<net.catharos.societies.database.layout.tables.records.SocietiesMembersRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<net.catharos.societies.database.layout.tables.records.SocietiesMembersRecord>>asList(net.catharos.societies.database.layout.Keys.KEY_SOCIETIES_MEMBERS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<net.catharos.societies.database.layout.tables.records.SocietiesMembersRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<net.catharos.societies.database.layout.tables.records.SocietiesMembersRecord, ?>>asList(net.catharos.societies.database.layout.Keys.FK_SOCIETIES_HAS_MEMBERS_SOCIETIES, net.catharos.societies.database.layout.Keys.FK_SOCIETIES_HAS_MEMBERS_MEMBERS1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public net.catharos.societies.database.layout.tables.SocietiesMembers as(java.lang.String alias) {
		return new net.catharos.societies.database.layout.tables.SocietiesMembers(alias, this);
	}

	/**
	 * Rename this table
	 */
	public net.catharos.societies.database.layout.tables.SocietiesMembers rename(java.lang.String name) {
		return new net.catharos.societies.database.layout.tables.SocietiesMembers(name, null);
	}
}
