/**
 * This class is generated by jOOQ
 */
package net.catharos.societies.database.sql.layout.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value = {"http://www.jooq.org", "3.3.2"},
        comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class RanksRecord extends org.jooq.impl.UpdatableRecordImpl<net.catharos.societies.database.sql.layout.tables.records.RanksRecord> implements org.jooq.Record2<byte[], java.lang.String> {

    private static final long serialVersionUID = 579066432;

    /**
     * Setter for <code>societies.ranks.uuid</code>.
     */
    public void setUuid(byte[] value) {
        setValue(0, value);
    }

    /**
     * Getter for <code>societies.ranks.uuid</code>.
     */
    public byte[] getUuid() {
        return (byte[]) getValue(0);
    }

    /**
     * Setter for <code>societies.ranks.name</code>.
     */
    public void setName(java.lang.String value) {
        setValue(1, value);
    }

    /**
     * Getter for <code>societies.ranks.name</code>.
     */
    public java.lang.String getName() {
        return (java.lang.String) getValue(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Record2<byte[], java.lang.String> key() {
        return (org.jooq.Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Row2<byte[], java.lang.String> fieldsRow() {
        return (org.jooq.Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Row2<byte[], java.lang.String> valuesRow() {
        return (org.jooq.Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Field<byte[]> field1() {
        return net.catharos.societies.database.sql.layout.tables.Ranks.RANKS.UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Field<java.lang.String> field2() {
        return net.catharos.societies.database.sql.layout.tables.Ranks.RANKS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value1() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.lang.String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RanksRecord value1(byte[] value) {
        setUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RanksRecord value2(java.lang.String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RanksRecord values(byte[] value1, java.lang.String value2) {
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RanksRecord
     */
    public RanksRecord() {
        super(net.catharos.societies.database.sql.layout.tables.Ranks.RANKS);
    }

    /**
     * Create a detached, initialised RanksRecord
     */
    public RanksRecord(byte[] uuid, java.lang.String name) {
        super(net.catharos.societies.database.sql.layout.tables.Ranks.RANKS);

        setValue(0, uuid);
        setValue(1, name);
    }
}
