/**
 * This class is generated by jOOQ
 */
package net.catharos.societies.database.sql.layout.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value = {"http://www.jooq.org", "3.3.2"},
        comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class SocietiesRecord extends org.jooq.impl.UpdatableRecordImpl<net.catharos.societies.database.sql.layout.tables.records.SocietiesRecord> implements org.jooq.Record6<byte[], java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.Short> {

    private static final long serialVersionUID = -753465922;

    /**
     * Setter for <code>societies.societies.uuid</code>.
     */
    public void setUuid(byte[] value) {
        setValue(0, value);
    }

    /**
     * Getter for <code>societies.societies.uuid</code>.
     */
    public byte[] getUuid() {
        return (byte[]) getValue(0);
    }

    /**
     * Setter for <code>societies.societies.name</code>.
     */
    public void setName(java.lang.String value) {
        setValue(1, value);
    }

    /**
     * Getter for <code>societies.societies.name</code>.
     */
    public java.lang.String getName() {
        return (java.lang.String) getValue(1);
    }

    /**
     * Setter for <code>societies.societies.tag</code>.
     */
    public void setTag(java.lang.String value) {
        setValue(2, value);
    }

    /**
     * Getter for <code>societies.societies.tag</code>.
     */
    public java.lang.String getTag() {
        return (java.lang.String) getValue(2);
    }

    /**
     * Setter for <code>societies.societies.clean_tag</code>.
     */
    public void setCleanTag(java.lang.String value) {
        setValue(3, value);
    }

    /**
     * Getter for <code>societies.societies.clean_tag</code>.
     */
    public java.lang.String getCleanTag() {
        return (java.lang.String) getValue(3);
    }

    /**
     * Setter for <code>societies.societies.created</code>.
     */
    public void setCreated(java.sql.Timestamp value) {
        setValue(4, value);
    }

    /**
     * Getter for <code>societies.societies.created</code>.
     */
    public java.sql.Timestamp getCreated() {
        return (java.sql.Timestamp) getValue(4);
    }

    /**
     * Setter for <code>societies.societies.state</code>.
     */
    public void setState(java.lang.Short value) {
        setValue(5, value);
    }

    /**
     * Getter for <code>societies.societies.state</code>.
     */
    public java.lang.Short getState() {
        return (java.lang.Short) getValue(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Record2<byte[], java.lang.String> key() {
        return (org.jooq.Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Row6<byte[], java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.Short> fieldsRow() {
        return (org.jooq.Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Row6<byte[], java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.Short> valuesRow() {
        return (org.jooq.Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Field<byte[]> field1() {
        return net.catharos.societies.database.sql.layout.tables.Societies.SOCIETIES.UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Field<java.lang.String> field2() {
        return net.catharos.societies.database.sql.layout.tables.Societies.SOCIETIES.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Field<java.lang.String> field3() {
        return net.catharos.societies.database.sql.layout.tables.Societies.SOCIETIES.TAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Field<java.lang.String> field4() {
        return net.catharos.societies.database.sql.layout.tables.Societies.SOCIETIES.CLEAN_TAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Field<java.sql.Timestamp> field5() {
        return net.catharos.societies.database.sql.layout.tables.Societies.SOCIETIES.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Field<java.lang.Short> field6() {
        return net.catharos.societies.database.sql.layout.tables.Societies.SOCIETIES.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value1() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.lang.String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.lang.String value3() {
        return getTag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.lang.String value4() {
        return getCleanTag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.sql.Timestamp value5() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.lang.Short value6() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SocietiesRecord value1(byte[] value) {
        setUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SocietiesRecord value2(java.lang.String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SocietiesRecord value3(java.lang.String value) {
        setTag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SocietiesRecord value4(java.lang.String value) {
        setCleanTag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SocietiesRecord value5(java.sql.Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SocietiesRecord value6(java.lang.Short value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SocietiesRecord values(byte[] value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.sql.Timestamp value5, java.lang.Short value6) {
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SocietiesRecord
     */
    public SocietiesRecord() {
        super(net.catharos.societies.database.sql.layout.tables.Societies.SOCIETIES);
    }

    /**
     * Create a detached, initialised SocietiesRecord
     */
    public SocietiesRecord(byte[] uuid, java.lang.String name, java.lang.String tag, java.lang.String cleanTag, java.sql.Timestamp created, java.lang.Short state) {
        super(net.catharos.societies.database.sql.layout.tables.Societies.SOCIETIES);

        setValue(0, uuid);
        setValue(1, name);
        setValue(2, tag);
        setValue(3, cleanTag);
        setValue(4, created);
        setValue(5, state);
    }
}
