/**
 * This class is generated by jOOQ
 */
package net.catharos.societies.database.sql.layout.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value = {"http://www.jooq.org", "3.3.2"},
        comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({"all", "unchecked", "rawtypes"})
public class SocietiesRanksRecord extends org.jooq.impl.UpdatableRecordImpl<net.catharos.societies.database.sql.layout.tables.records.SocietiesRanksRecord> implements org.jooq.Record2<byte[], byte[]> {

    private static final long serialVersionUID = 2061055930;

    /**
     * Setter for <code>societies.societies_ranks.society</code>.
     */
    public void setSociety(byte[] value) {
        setValue(0, value);
    }

    /**
     * Getter for <code>societies.societies_ranks.society</code>.
     */
    public byte[] getSociety() {
        return (byte[]) getValue(0);
    }

    /**
     * Setter for <code>societies.societies_ranks.rank</code>.
     */
    public void setRank(byte[] value) {
        setValue(1, value);
    }

    /**
     * Getter for <code>societies.societies_ranks.rank</code>.
     */
    public byte[] getRank() {
        return (byte[]) getValue(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Record2<byte[], byte[]> key() {
        return (org.jooq.Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Row2<byte[], byte[]> fieldsRow() {
        return (org.jooq.Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Row2<byte[], byte[]> valuesRow() {
        return (org.jooq.Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Field<byte[]> field1() {
        return net.catharos.societies.database.sql.layout.tables.SocietiesRanks.SOCIETIES_RANKS.SOCIETY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public org.jooq.Field<byte[]> field2() {
        return net.catharos.societies.database.sql.layout.tables.SocietiesRanks.SOCIETIES_RANKS.RANK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value1() {
        return getSociety();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value2() {
        return getRank();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SocietiesRanksRecord value1(byte[] value) {
        setSociety(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SocietiesRanksRecord value2(byte[] value) {
        setRank(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SocietiesRanksRecord values(byte[] value1, byte[] value2) {
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SocietiesRanksRecord
     */
    public SocietiesRanksRecord() {
        super(net.catharos.societies.database.sql.layout.tables.SocietiesRanks.SOCIETIES_RANKS);
    }

    /**
     * Create a detached, initialised SocietiesRanksRecord
     */
    public SocietiesRanksRecord(byte[] society, byte[] rank) {
        super(net.catharos.societies.database.sql.layout.tables.SocietiesRanks.SOCIETIES_RANKS);

        setValue(0, society);
        setValue(1, rank);
    }
}
