/**
 * This class is generated by jOOQ
 */
package org.societies.database.sql.layout.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LandsRecord extends org.jooq.impl.UpdatableRecordImpl<org.societies.database.sql.layout.tables.records.LandsRecord> implements org.jooq.Record2<byte[], byte[]> {

	private static final long serialVersionUID = -216456489;

	/**
	 * Setter for <code>societies.lands.uuid</code>.
	 */
	public void setUuid(byte[] value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>societies.lands.uuid</code>.
	 */
	public byte[] getUuid() {
		return (byte[]) getValue(0);
	}

	/**
	 * Setter for <code>societies.lands.origin</code>.
	 */
	public void setOrigin(byte[] value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>societies.lands.origin</code>.
	 */
	public byte[] getOrigin() {
		return (byte[]) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<byte[]> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<byte[], byte[]> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<byte[], byte[]> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field1() {
		return org.societies.database.sql.layout.tables.Lands.LANDS.UUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field2() {
		return org.societies.database.sql.layout.tables.Lands.LANDS.ORIGIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value1() {
		return getUuid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value2() {
		return getOrigin();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LandsRecord value1(byte[] value) {
		setUuid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LandsRecord value2(byte[] value) {
		setOrigin(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LandsRecord values(byte[] value1, byte[] value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached LandsRecord
	 */
	public LandsRecord() {
		super(org.societies.database.sql.layout.tables.Lands.LANDS);
	}

	/**
	 * Create a detached, initialised LandsRecord
	 */
	public LandsRecord(byte[] uuid, byte[] origin) {
		super(org.societies.database.sql.layout.tables.Lands.LANDS);

		setValue(0, uuid);
		setValue(1, origin);
	}
}
