/**
 * This class is generated by jOOQ
 */
package org.societies.database.sql.layout.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MembersRanksRecord extends org.jooq.impl.UpdatableRecordImpl<org.societies.database.sql.layout.tables.records.MembersRanksRecord> implements org.jooq.Record2<java.util.UUID, java.util.UUID> {

	private static final long serialVersionUID = 670492108;

	/**
	 * Setter for <code>societies.members_ranks.member</code>.
	 */
	public void setMember(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>societies.members_ranks.member</code>.
	 */
	public java.util.UUID getMember() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>societies.members_ranks.rank</code>.
	 */
	public void setRank(java.util.UUID value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>societies.members_ranks.rank</code>.
	 */
	public java.util.UUID getRank() {
		return (java.util.UUID) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.util.UUID, java.util.UUID> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.util.UUID, java.util.UUID> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.util.UUID, java.util.UUID> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return org.societies.database.sql.layout.tables.MembersRanks.MEMBERS_RANKS.MEMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field2() {
		return org.societies.database.sql.layout.tables.MembersRanks.MEMBERS_RANKS.RANK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getMember();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value2() {
		return getRank();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MembersRanksRecord value1(java.util.UUID value) {
		setMember(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MembersRanksRecord value2(java.util.UUID value) {
		setRank(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MembersRanksRecord values(java.util.UUID value1, java.util.UUID value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MembersRanksRecord
	 */
	public MembersRanksRecord() {
		super(org.societies.database.sql.layout.tables.MembersRanks.MEMBERS_RANKS);
	}

	/**
	 * Create a detached, initialised MembersRanksRecord
	 */
	public MembersRanksRecord(java.util.UUID member, java.util.UUID rank) {
		super(org.societies.database.sql.layout.tables.MembersRanks.MEMBERS_RANKS);

		setValue(0, member);
		setValue(1, rank);
	}
}
