/**
 * This class is generated by jOOQ
 */
package org.societies.database.sql.layout.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MemberSettingsRecord extends org.jooq.impl.UpdatableRecordImpl<org.societies.database.sql.layout.tables.records.MemberSettingsRecord> implements org.jooq.Record4<java.util.UUID, java.util.UUID, org.jooq.types.UShort, byte[]> {

	private static final long serialVersionUID = 1809716328;

	/**
	 * Setter for <code>societies.member_settings.subject_uuid</code>.
	 */
	public void setSubjectUuid(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>societies.member_settings.subject_uuid</code>.
	 */
	public java.util.UUID getSubjectUuid() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>societies.member_settings.target_uuid</code>.
	 */
	public void setTargetUuid(java.util.UUID value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>societies.member_settings.target_uuid</code>.
	 */
	public java.util.UUID getTargetUuid() {
		return (java.util.UUID) getValue(1);
	}

	/**
	 * Setter for <code>societies.member_settings.setting</code>.
	 */
	public void setSetting(org.jooq.types.UShort value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>societies.member_settings.setting</code>.
	 */
	public org.jooq.types.UShort getSetting() {
		return (org.jooq.types.UShort) getValue(2);
	}

	/**
	 * Setter for <code>societies.member_settings.value</code>.
	 */
	public void setValue(byte[] value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>societies.member_settings.value</code>.
	 */
	public byte[] getValue() {
		return (byte[]) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record3<java.util.UUID, java.util.UUID, org.jooq.types.UShort> key() {
		return (org.jooq.Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.util.UUID, java.util.UUID, org.jooq.types.UShort, byte[]> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.util.UUID, java.util.UUID, org.jooq.types.UShort, byte[]> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return org.societies.database.sql.layout.tables.MemberSettings.MEMBER_SETTINGS.SUBJECT_UUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field2() {
		return org.societies.database.sql.layout.tables.MemberSettings.MEMBER_SETTINGS.TARGET_UUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UShort> field3() {
		return org.societies.database.sql.layout.tables.MemberSettings.MEMBER_SETTINGS.SETTING;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field4() {
		return org.societies.database.sql.layout.tables.MemberSettings.MEMBER_SETTINGS.VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getSubjectUuid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value2() {
		return getTargetUuid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UShort value3() {
		return getSetting();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value4() {
		return getValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MemberSettingsRecord value1(java.util.UUID value) {
		setSubjectUuid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MemberSettingsRecord value2(java.util.UUID value) {
		setTargetUuid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MemberSettingsRecord value3(org.jooq.types.UShort value) {
		setSetting(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MemberSettingsRecord value4(byte[] value) {
		setValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MemberSettingsRecord values(java.util.UUID value1, java.util.UUID value2, org.jooq.types.UShort value3, byte[] value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MemberSettingsRecord
	 */
	public MemberSettingsRecord() {
		super(org.societies.database.sql.layout.tables.MemberSettings.MEMBER_SETTINGS);
	}

	/**
	 * Create a detached, initialised MemberSettingsRecord
	 */
	public MemberSettingsRecord(java.util.UUID subjectUuid, java.util.UUID targetUuid, org.jooq.types.UShort setting, byte[] value) {
		super(org.societies.database.sql.layout.tables.MemberSettings.MEMBER_SETTINGS);

		setValue(0, subjectUuid);
		setValue(1, targetUuid);
		setValue(2, setting);
		setValue(3, value);
	}
}
