/**
 * This class is generated by jOOQ
 */
package org.societies.database.sql.layout.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RelationsRecord extends org.jooq.impl.UpdatableRecordImpl<org.societies.database.sql.layout.tables.records.RelationsRecord> implements org.jooq.Record3<java.util.UUID, java.util.UUID, java.lang.Short> {

	private static final long serialVersionUID = -1562854956;

	/**
	 * Setter for <code>societies.relations.society</code>.
	 */
	public void setSociety(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>societies.relations.society</code>.
	 */
	public java.util.UUID getSociety() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>societies.relations.society2</code>.
	 */
	public void setSociety2(java.util.UUID value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>societies.relations.society2</code>.
	 */
	public java.util.UUID getSociety2() {
		return (java.util.UUID) getValue(1);
	}

	/**
	 * Setter for <code>societies.relations.type</code>.
	 */
	public void setType(java.lang.Short value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>societies.relations.type</code>.
	 */
	public java.lang.Short getType() {
		return (java.lang.Short) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.util.UUID, java.util.UUID> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.util.UUID, java.util.UUID, java.lang.Short> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.util.UUID, java.util.UUID, java.lang.Short> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return org.societies.database.sql.layout.tables.Relations.RELATIONS.SOCIETY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field2() {
		return org.societies.database.sql.layout.tables.Relations.RELATIONS.SOCIETY2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Short> field3() {
		return org.societies.database.sql.layout.tables.Relations.RELATIONS.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getSociety();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value2() {
		return getSociety2();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Short value3() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RelationsRecord value1(java.util.UUID value) {
		setSociety(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RelationsRecord value2(java.util.UUID value) {
		setSociety2(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RelationsRecord value3(java.lang.Short value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RelationsRecord values(java.util.UUID value1, java.util.UUID value2, java.lang.Short value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RelationsRecord
	 */
	public RelationsRecord() {
		super(org.societies.database.sql.layout.tables.Relations.RELATIONS);
	}

	/**
	 * Create a detached, initialised RelationsRecord
	 */
	public RelationsRecord(java.util.UUID society, java.util.UUID society2, java.lang.Short type) {
		super(org.societies.database.sql.layout.tables.Relations.RELATIONS);

		setValue(0, society);
		setValue(1, society2);
		setValue(2, type);
	}
}
