/**
 * This class is generated by jOOQ
 */
package org.societies.database.sql.layout.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SiegesRecord extends org.jooq.impl.UpdatableRecordImpl<org.societies.database.sql.layout.tables.records.SiegesRecord> implements org.jooq.Record8<byte[], byte[], byte[], java.lang.Short, java.lang.Short, java.lang.Short, java.sql.Timestamp, byte[]> {

	private static final long serialVersionUID = 1745449670;

	/**
	 * Setter for <code>societies.sieges.uuid</code>.
	 */
	public void setUuid(byte[] value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>societies.sieges.uuid</code>.
	 */
	public byte[] getUuid() {
		return (byte[]) getValue(0);
	}

	/**
	 * Setter for <code>societies.sieges.society</code>.
	 */
	public void setSociety(byte[] value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>societies.sieges.society</code>.
	 */
	public byte[] getSociety() {
		return (byte[]) getValue(1);
	}

	/**
	 * Setter for <code>societies.sieges.city</code>.
	 */
	public void setCity(byte[] value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>societies.sieges.city</code>.
	 */
	public byte[] getCity() {
		return (byte[]) getValue(2);
	}

	/**
	 * Setter for <code>societies.sieges.x</code>.
	 */
	public void setX(java.lang.Short value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>societies.sieges.x</code>.
	 */
	public java.lang.Short getX() {
		return (java.lang.Short) getValue(3);
	}

	/**
	 * Setter for <code>societies.sieges.y</code>.
	 */
	public void setY(java.lang.Short value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>societies.sieges.y</code>.
	 */
	public java.lang.Short getY() {
		return (java.lang.Short) getValue(4);
	}

	/**
	 * Setter for <code>societies.sieges.z</code>.
	 */
	public void setZ(java.lang.Short value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>societies.sieges.z</code>.
	 */
	public java.lang.Short getZ() {
		return (java.lang.Short) getValue(5);
	}

	/**
	 * Setter for <code>societies.sieges.created</code>.
	 */
	public void setCreated(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>societies.sieges.created</code>.
	 */
	public java.sql.Timestamp getCreated() {
		return (java.sql.Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>societies.sieges.wager</code>.
	 */
	public void setWager(byte[] value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>societies.sieges.wager</code>.
	 */
	public byte[] getWager() {
		return (byte[]) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record3<byte[], byte[], byte[]> key() {
		return (org.jooq.Record3) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<byte[], byte[], byte[], java.lang.Short, java.lang.Short, java.lang.Short, java.sql.Timestamp, byte[]> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<byte[], byte[], byte[], java.lang.Short, java.lang.Short, java.lang.Short, java.sql.Timestamp, byte[]> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field1() {
		return org.societies.database.sql.layout.tables.Sieges.SIEGES.UUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field2() {
		return org.societies.database.sql.layout.tables.Sieges.SIEGES.SOCIETY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field3() {
		return org.societies.database.sql.layout.tables.Sieges.SIEGES.CITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Short> field4() {
		return org.societies.database.sql.layout.tables.Sieges.SIEGES.X;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Short> field5() {
		return org.societies.database.sql.layout.tables.Sieges.SIEGES.Y;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Short> field6() {
		return org.societies.database.sql.layout.tables.Sieges.SIEGES.Z;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return org.societies.database.sql.layout.tables.Sieges.SIEGES.CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field8() {
		return org.societies.database.sql.layout.tables.Sieges.SIEGES.WAGER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value1() {
		return getUuid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value2() {
		return getSociety();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value3() {
		return getCity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Short value4() {
		return getX();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Short value5() {
		return getY();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Short value6() {
		return getZ();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value8() {
		return getWager();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SiegesRecord value1(byte[] value) {
		setUuid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SiegesRecord value2(byte[] value) {
		setSociety(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SiegesRecord value3(byte[] value) {
		setCity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SiegesRecord value4(java.lang.Short value) {
		setX(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SiegesRecord value5(java.lang.Short value) {
		setY(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SiegesRecord value6(java.lang.Short value) {
		setZ(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SiegesRecord value7(java.sql.Timestamp value) {
		setCreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SiegesRecord value8(byte[] value) {
		setWager(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SiegesRecord values(byte[] value1, byte[] value2, byte[] value3, java.lang.Short value4, java.lang.Short value5, java.lang.Short value6, java.sql.Timestamp value7, byte[] value8) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SiegesRecord
	 */
	public SiegesRecord() {
		super(org.societies.database.sql.layout.tables.Sieges.SIEGES);
	}

	/**
	 * Create a detached, initialised SiegesRecord
	 */
	public SiegesRecord(byte[] uuid, byte[] society, byte[] city, java.lang.Short x, java.lang.Short y, java.lang.Short z, java.sql.Timestamp created, byte[] wager) {
		super(org.societies.database.sql.layout.tables.Sieges.SIEGES);

		setValue(0, uuid);
		setValue(1, society);
		setValue(2, city);
		setValue(3, x);
		setValue(4, y);
		setValue(5, z);
		setValue(6, created);
		setValue(7, wager);
	}
}
