/**
 * This class is generated by jOOQ
 */
package org.societies.database.sql.layout.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SocietiesRanksRecord extends org.jooq.impl.UpdatableRecordImpl<org.societies.database.sql.layout.tables.records.SocietiesRanksRecord> implements org.jooq.Record2<java.util.UUID, java.util.UUID> {

	private static final long serialVersionUID = 1550661557;

	/**
	 * Setter for <code>societies.societies_ranks.society</code>.
	 */
	public void setSociety(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>societies.societies_ranks.society</code>.
	 */
	public java.util.UUID getSociety() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>societies.societies_ranks.rank</code>.
	 */
	public void setRank(java.util.UUID value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>societies.societies_ranks.rank</code>.
	 */
	public java.util.UUID getRank() {
		return (java.util.UUID) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.util.UUID, java.util.UUID> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.util.UUID, java.util.UUID> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.util.UUID, java.util.UUID> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return org.societies.database.sql.layout.tables.SocietiesRanks.SOCIETIES_RANKS.SOCIETY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field2() {
		return org.societies.database.sql.layout.tables.SocietiesRanks.SOCIETIES_RANKS.RANK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getSociety();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value2() {
		return getRank();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SocietiesRanksRecord value1(java.util.UUID value) {
		setSociety(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SocietiesRanksRecord value2(java.util.UUID value) {
		setRank(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SocietiesRanksRecord values(java.util.UUID value1, java.util.UUID value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SocietiesRanksRecord
	 */
	public SocietiesRanksRecord() {
		super(org.societies.database.sql.layout.tables.SocietiesRanks.SOCIETIES_RANKS);
	}

	/**
	 * Create a detached, initialised SocietiesRanksRecord
	 */
	public SocietiesRanksRecord(java.util.UUID society, java.util.UUID rank) {
		super(org.societies.database.sql.layout.tables.SocietiesRanks.SOCIETIES_RANKS);

		setValue(0, society);
		setValue(1, rank);
	}
}
