/**
 * This class is generated by jOOQ
 */
package org.societies.database.sql.layout.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.4" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SocietiesLocksRecord extends org.jooq.impl.UpdatableRecordImpl<org.societies.database.sql.layout.tables.records.SocietiesLocksRecord> implements org.jooq.Record1<java.lang.Short> {

	private static final long serialVersionUID = 2002374945;

	/**
	 * Setter for <code>societies.societies_locks.id</code>.
	 */
	public void setId(java.lang.Short value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>societies.societies_locks.id</code>.
	 */
	public java.lang.Short getId() {
		return (java.lang.Short) getValue(0);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Short> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record1 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row1<java.lang.Short> fieldsRow() {
		return (org.jooq.Row1) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row1<java.lang.Short> valuesRow() {
		return (org.jooq.Row1) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Short> field1() {
		return org.societies.database.sql.layout.tables.SocietiesLocks.SOCIETIES_LOCKS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Short value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SocietiesLocksRecord value1(java.lang.Short value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SocietiesLocksRecord values(java.lang.Short value1) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SocietiesLocksRecord
	 */
	public SocietiesLocksRecord() {
		super(org.societies.database.sql.layout.tables.SocietiesLocks.SOCIETIES_LOCKS);
	}

	/**
	 * Create a detached, initialised SocietiesLocksRecord
	 */
	public SocietiesLocksRecord(java.lang.Short id) {
		super(org.societies.database.sql.layout.tables.SocietiesLocks.SOCIETIES_LOCKS);

		setValue(0, id);
	}
}
