/**
 * This class is generated by jOOQ
 */
package net.catharos.societies.database.layout.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MembersRanksRecord extends org.jooq.impl.UpdatableRecordImpl<net.catharos.societies.database.layout.tables.records.MembersRanksRecord> implements org.jooq.Record2<byte[], byte[]> {

	private static final long serialVersionUID = 716646463;

	/**
	 * Setter for <code>societies.members_ranks.member</code>. 
	 */
	public void setMember(byte[] value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>societies.members_ranks.member</code>. 
	 */
	public byte[] getMember() {
		return (byte[]) getValue(0);
	}

	/**
	 * Setter for <code>societies.members_ranks.rank</code>. 
	 */
	public void setRank(byte[] value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>societies.members_ranks.rank</code>. 
	 */
	public byte[] getRank() {
		return (byte[]) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<byte[], byte[]> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<byte[], byte[]> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<byte[], byte[]> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field1() {
		return net.catharos.societies.database.layout.tables.MembersRanks.MEMBERS_RANKS.MEMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field2() {
		return net.catharos.societies.database.layout.tables.MembersRanks.MEMBERS_RANKS.RANK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value1() {
		return getMember();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value2() {
		return getRank();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MembersRanksRecord
	 */
	public MembersRanksRecord() {
		super(net.catharos.societies.database.layout.tables.MembersRanks.MEMBERS_RANKS);
	}

	/**
	 * Create a detached, initialised MembersRanksRecord
	 */
	public MembersRanksRecord(byte[] member, byte[] rank) {
		super(net.catharos.societies.database.layout.tables.MembersRanks.MEMBERS_RANKS);

		setValue(0, member);
		setValue(1, rank);
	}
}
