/**
 * This class is generated by jOOQ
 */
package net.catharos.societies.database.layout.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MembersRanksRecord extends org.jooq.impl.UpdatableRecordImpl<net.catharos.societies.database.layout.tables.records.MembersRanksRecord> implements org.jooq.Record2<byte[], byte[]> {

	private static final long serialVersionUID = -174808199;

	/**
	 * Setter for <code>societies.members_ranks.members_uuid</code>. 
	 */
	public void setMembersUuid(byte[] value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>societies.members_ranks.members_uuid</code>. 
	 */
	public byte[] getMembersUuid() {
		return (byte[]) getValue(0);
	}

	/**
	 * Setter for <code>societies.members_ranks.ranks_uuid</code>. 
	 */
	public void setRanksUuid(byte[] value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>societies.members_ranks.ranks_uuid</code>. 
	 */
	public byte[] getRanksUuid() {
		return (byte[]) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<byte[], byte[]> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<byte[], byte[]> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<byte[], byte[]> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field1() {
		return net.catharos.societies.database.layout.tables.MembersRanks.MEMBERS_RANKS.MEMBERS_UUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field2() {
		return net.catharos.societies.database.layout.tables.MembersRanks.MEMBERS_RANKS.RANKS_UUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value1() {
		return getMembersUuid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value2() {
		return getRanksUuid();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MembersRanksRecord
	 */
	public MembersRanksRecord() {
		super(net.catharos.societies.database.layout.tables.MembersRanks.MEMBERS_RANKS);
	}

	/**
	 * Create a detached, initialised MembersRanksRecord
	 */
	public MembersRanksRecord(byte[] membersUuid, byte[] ranksUuid) {
		super(net.catharos.societies.database.layout.tables.MembersRanks.MEMBERS_RANKS);

		setValue(0, membersUuid);
		setValue(1, ranksUuid);
	}
}
