/**
 * This class is generated by jOOQ
 */
package net.catharos.societies.database.layout.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RanksPermissionsRecord extends org.jooq.impl.UpdatableRecordImpl<net.catharos.societies.database.layout.tables.records.RanksPermissionsRecord> implements org.jooq.Record2<byte[], java.lang.Integer> {

	private static final long serialVersionUID = 1860684097;

	/**
	 * Setter for <code>societies.ranks_permissions.rank</code>. 
	 */
	public void setRank(byte[] value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>societies.ranks_permissions.rank</code>. 
	 */
	public byte[] getRank() {
		return (byte[]) getValue(0);
	}

	/**
	 * Setter for <code>societies.ranks_permissions.permission</code>. 
	 */
	public void setPermission(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>societies.ranks_permissions.permission</code>. 
	 */
	public java.lang.Integer getPermission() {
		return (java.lang.Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<byte[], java.lang.Integer> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<byte[], java.lang.Integer> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<byte[], java.lang.Integer> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field1() {
		return net.catharos.societies.database.layout.tables.RanksPermissions.RANKS_PERMISSIONS.RANK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return net.catharos.societies.database.layout.tables.RanksPermissions.RANKS_PERMISSIONS.PERMISSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value1() {
		return getRank();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getPermission();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RanksPermissionsRecord
	 */
	public RanksPermissionsRecord() {
		super(net.catharos.societies.database.layout.tables.RanksPermissions.RANKS_PERMISSIONS);
	}

	/**
	 * Create a detached, initialised RanksPermissionsRecord
	 */
	public RanksPermissionsRecord(byte[] rank, java.lang.Integer permission) {
		super(net.catharos.societies.database.layout.tables.RanksPermissions.RANKS_PERMISSIONS);

		setValue(0, rank);
		setValue(1, permission);
	}
}
