/**
 * This class is generated by jOOQ
 */
package net.catharos.societies.database.layout.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SocietiesRanksRecord extends org.jooq.impl.UpdatableRecordImpl<net.catharos.societies.database.layout.tables.records.SocietiesRanksRecord> implements org.jooq.Record2<byte[], byte[]> {

	private static final long serialVersionUID = 2091656697;

	/**
	 * Setter for <code>societies.societies_ranks.societies</code>. 
	 */
	public void setSocieties(byte[] value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>societies.societies_ranks.societies</code>. 
	 */
	public byte[] getSocieties() {
		return (byte[]) getValue(0);
	}

	/**
	 * Setter for <code>societies.societies_ranks.ranks</code>. 
	 */
	public void setRanks(byte[] value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>societies.societies_ranks.ranks</code>. 
	 */
	public byte[] getRanks() {
		return (byte[]) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<byte[], byte[]> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<byte[], byte[]> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<byte[], byte[]> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field1() {
		return net.catharos.societies.database.layout.tables.SocietiesRanks.SOCIETIES_RANKS.SOCIETIES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field2() {
		return net.catharos.societies.database.layout.tables.SocietiesRanks.SOCIETIES_RANKS.RANKS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value1() {
		return getSocieties();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value2() {
		return getRanks();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SocietiesRanksRecord
	 */
	public SocietiesRanksRecord() {
		super(net.catharos.societies.database.layout.tables.SocietiesRanks.SOCIETIES_RANKS);
	}

	/**
	 * Create a detached, initialised SocietiesRanksRecord
	 */
	public SocietiesRanksRecord(byte[] societies, byte[] ranks) {
		super(net.catharos.societies.database.layout.tables.SocietiesRanks.SOCIETIES_RANKS);

		setValue(0, societies);
		setValue(1, ranks);
	}
}
