/**
 * This class is generated by jOOQ
 */
package net.catharos.societies.database.layout.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SocietiesRecord extends org.jooq.impl.UpdatableRecordImpl<net.catharos.societies.database.layout.tables.records.SocietiesRecord> implements org.jooq.Record5<byte[], java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.Short> {

	private static final long serialVersionUID = 1731413761;

	/**
	 * Setter for <code>societies.societies.uuid</code>. 
	 */
	public void setUuid(byte[] value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>societies.societies.uuid</code>. 
	 */
	public byte[] getUuid() {
		return (byte[]) getValue(0);
	}

	/**
	 * Setter for <code>societies.societies.name</code>. 
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>societies.societies.name</code>. 
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>societies.societies.tag</code>. 
	 */
	public void setTag(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>societies.societies.tag</code>. 
	 */
	public java.lang.String getTag() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>societies.societies.created</code>. 
	 */
	public void setCreated(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>societies.societies.created</code>. 
	 */
	public java.sql.Timestamp getCreated() {
		return (java.sql.Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>societies.societies.state</code>. 
	 */
	public void setState(java.lang.Short value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>societies.societies.state</code>. 
	 */
	public java.lang.Short getState() {
		return (java.lang.Short) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<byte[]> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<byte[], java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.Short> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<byte[], java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.Short> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field1() {
		return net.catharos.societies.database.layout.tables.Societies.SOCIETIES.UUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return net.catharos.societies.database.layout.tables.Societies.SOCIETIES.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return net.catharos.societies.database.layout.tables.Societies.SOCIETIES.TAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return net.catharos.societies.database.layout.tables.Societies.SOCIETIES.CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Short> field5() {
		return net.catharos.societies.database.layout.tables.Societies.SOCIETIES.STATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value1() {
		return getUuid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getTag();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Short value5() {
		return getState();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SocietiesRecord
	 */
	public SocietiesRecord() {
		super(net.catharos.societies.database.layout.tables.Societies.SOCIETIES);
	}

	/**
	 * Create a detached, initialised SocietiesRecord
	 */
	public SocietiesRecord(byte[] uuid, java.lang.String name, java.lang.String tag, java.sql.Timestamp created, java.lang.Short state) {
		super(net.catharos.societies.database.layout.tables.Societies.SOCIETIES);

		setValue(0, uuid);
		setValue(1, name);
		setValue(2, tag);
		setValue(3, created);
		setValue(4, state);
	}
}
