/**
 * This class is generated by jOOQ
 */
package net.catharos.societies.database.layout.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SocietiesMembersRecord extends org.jooq.impl.UpdatableRecordImpl<net.catharos.societies.database.layout.tables.records.SocietiesMembersRecord> implements org.jooq.Record2<byte[], byte[]> {

	private static final long serialVersionUID = 410404971;

	/**
	 * Setter for <code>societies.societies_members.societies_uuid</code>. 
	 */
	public void setSocietiesUuid(byte[] value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>societies.societies_members.societies_uuid</code>. 
	 */
	public byte[] getSocietiesUuid() {
		return (byte[]) getValue(0);
	}

	/**
	 * Setter for <code>societies.societies_members.members_uuid</code>. 
	 */
	public void setMembersUuid(byte[] value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>societies.societies_members.members_uuid</code>. 
	 */
	public byte[] getMembersUuid() {
		return (byte[]) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<byte[], byte[]> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<byte[], byte[]> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<byte[], byte[]> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field1() {
		return net.catharos.societies.database.layout.tables.SocietiesMembers.SOCIETIES_MEMBERS.SOCIETIES_UUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<byte[]> field2() {
		return net.catharos.societies.database.layout.tables.SocietiesMembers.SOCIETIES_MEMBERS.MEMBERS_UUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value1() {
		return getSocietiesUuid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public byte[] value2() {
		return getMembersUuid();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SocietiesMembersRecord
	 */
	public SocietiesMembersRecord() {
		super(net.catharos.societies.database.layout.tables.SocietiesMembers.SOCIETIES_MEMBERS);
	}

	/**
	 * Create a detached, initialised SocietiesMembersRecord
	 */
	public SocietiesMembersRecord(byte[] societiesUuid, byte[] membersUuid) {
		super(net.catharos.societies.database.layout.tables.SocietiesMembers.SOCIETIES_MEMBERS);

		setValue(0, societiesUuid);
		setValue(1, membersUuid);
	}
}
