/**
 * This class is generated by jOOQ
 */
package net.catharos.societies.database.layout;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>societies</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<net.catharos.societies.database.layout.tables.records.MembersRecord> KEY_MEMBERS_PRIMARY = UniqueKeys0.KEY_MEMBERS_PRIMARY;
	public static final org.jooq.UniqueKey<net.catharos.societies.database.layout.tables.records.MembersRanksRecord> KEY_MEMBERS_RANKS_PRIMARY = UniqueKeys0.KEY_MEMBERS_RANKS_PRIMARY;
	public static final org.jooq.UniqueKey<net.catharos.societies.database.layout.tables.records.RanksRecord> KEY_RANKS_PRIMARY = UniqueKeys0.KEY_RANKS_PRIMARY;
	public static final org.jooq.UniqueKey<net.catharos.societies.database.layout.tables.records.RanksPermissionsRecord> KEY_RANKS_PERMISSIONS_PRIMARY = UniqueKeys0.KEY_RANKS_PERMISSIONS_PRIMARY;
	public static final org.jooq.UniqueKey<net.catharos.societies.database.layout.tables.records.RelationsRecord> KEY_RELATIONS_PRIMARY = UniqueKeys0.KEY_RELATIONS_PRIMARY;
	public static final org.jooq.UniqueKey<net.catharos.societies.database.layout.tables.records.SocietiesRecord> KEY_SOCIETIES_PRIMARY = UniqueKeys0.KEY_SOCIETIES_PRIMARY;
	public static final org.jooq.UniqueKey<net.catharos.societies.database.layout.tables.records.SocietiesMembersRecord> KEY_SOCIETIES_MEMBERS_PRIMARY = UniqueKeys0.KEY_SOCIETIES_MEMBERS_PRIMARY;
	public static final org.jooq.UniqueKey<net.catharos.societies.database.layout.tables.records.SocietiesRanksRecord> KEY_SOCIETIES_RANKS_PRIMARY = UniqueKeys0.KEY_SOCIETIES_RANKS_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<net.catharos.societies.database.layout.tables.records.MembersRanksRecord, net.catharos.societies.database.layout.tables.records.MembersRecord> FK_MEMBERS_HAS_RANKS_MEMBERS1 = ForeignKeys0.FK_MEMBERS_HAS_RANKS_MEMBERS1;
	public static final org.jooq.ForeignKey<net.catharos.societies.database.layout.tables.records.MembersRanksRecord, net.catharos.societies.database.layout.tables.records.RanksRecord> FK_MEMBERS_HAS_RANKS_RANKS1 = ForeignKeys0.FK_MEMBERS_HAS_RANKS_RANKS1;
	public static final org.jooq.ForeignKey<net.catharos.societies.database.layout.tables.records.RanksPermissionsRecord, net.catharos.societies.database.layout.tables.records.RanksRecord> FK_RANKS_HAS_PERMISSIONS_RANKS1 = ForeignKeys0.FK_RANKS_HAS_PERMISSIONS_RANKS1;
	public static final org.jooq.ForeignKey<net.catharos.societies.database.layout.tables.records.RelationsRecord, net.catharos.societies.database.layout.tables.records.SocietiesRecord> FK_SOCIETIES_HAS_SOCIETIES_SOCIETIES1 = ForeignKeys0.FK_SOCIETIES_HAS_SOCIETIES_SOCIETIES1;
	public static final org.jooq.ForeignKey<net.catharos.societies.database.layout.tables.records.RelationsRecord, net.catharos.societies.database.layout.tables.records.SocietiesRecord> FK_SOCIETIES_HAS_SOCIETIES_SOCIETIES2 = ForeignKeys0.FK_SOCIETIES_HAS_SOCIETIES_SOCIETIES2;
	public static final org.jooq.ForeignKey<net.catharos.societies.database.layout.tables.records.SocietiesMembersRecord, net.catharos.societies.database.layout.tables.records.SocietiesRecord> FK_SOCIETIES_HAS_MEMBERS_SOCIETIES = ForeignKeys0.FK_SOCIETIES_HAS_MEMBERS_SOCIETIES;
	public static final org.jooq.ForeignKey<net.catharos.societies.database.layout.tables.records.SocietiesMembersRecord, net.catharos.societies.database.layout.tables.records.MembersRecord> FK_SOCIETIES_HAS_MEMBERS_MEMBERS1 = ForeignKeys0.FK_SOCIETIES_HAS_MEMBERS_MEMBERS1;
	public static final org.jooq.ForeignKey<net.catharos.societies.database.layout.tables.records.SocietiesRanksRecord, net.catharos.societies.database.layout.tables.records.SocietiesRecord> FK_SOCIETIES_HAS_RANKS_SOCIETIES2 = ForeignKeys0.FK_SOCIETIES_HAS_RANKS_SOCIETIES2;
	public static final org.jooq.ForeignKey<net.catharos.societies.database.layout.tables.records.SocietiesRanksRecord, net.catharos.societies.database.layout.tables.records.RanksRecord> FK_SOCIETIES_HAS_RANKS_RANKS2 = ForeignKeys0.FK_SOCIETIES_HAS_RANKS_RANKS2;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<net.catharos.societies.database.layout.tables.records.MembersRecord> KEY_MEMBERS_PRIMARY = createUniqueKey(net.catharos.societies.database.layout.tables.Members.MEMBERS, net.catharos.societies.database.layout.tables.Members.MEMBERS.UUID);
		public static final org.jooq.UniqueKey<net.catharos.societies.database.layout.tables.records.MembersRanksRecord> KEY_MEMBERS_RANKS_PRIMARY = createUniqueKey(net.catharos.societies.database.layout.tables.MembersRanks.MEMBERS_RANKS, net.catharos.societies.database.layout.tables.MembersRanks.MEMBERS_RANKS.MEMBER, net.catharos.societies.database.layout.tables.MembersRanks.MEMBERS_RANKS.RANK);
		public static final org.jooq.UniqueKey<net.catharos.societies.database.layout.tables.records.RanksRecord> KEY_RANKS_PRIMARY = createUniqueKey(net.catharos.societies.database.layout.tables.Ranks.RANKS, net.catharos.societies.database.layout.tables.Ranks.RANKS.UUID);
		public static final org.jooq.UniqueKey<net.catharos.societies.database.layout.tables.records.RanksPermissionsRecord> KEY_RANKS_PERMISSIONS_PRIMARY = createUniqueKey(net.catharos.societies.database.layout.tables.RanksPermissions.RANKS_PERMISSIONS, net.catharos.societies.database.layout.tables.RanksPermissions.RANKS_PERMISSIONS.RANK, net.catharos.societies.database.layout.tables.RanksPermissions.RANKS_PERMISSIONS.PERMISSION);
		public static final org.jooq.UniqueKey<net.catharos.societies.database.layout.tables.records.RelationsRecord> KEY_RELATIONS_PRIMARY = createUniqueKey(net.catharos.societies.database.layout.tables.Relations.RELATIONS, net.catharos.societies.database.layout.tables.Relations.RELATIONS.SOCIETY, net.catharos.societies.database.layout.tables.Relations.RELATIONS.SOCIETY2);
		public static final org.jooq.UniqueKey<net.catharos.societies.database.layout.tables.records.SocietiesRecord> KEY_SOCIETIES_PRIMARY = createUniqueKey(net.catharos.societies.database.layout.tables.Societies.SOCIETIES, net.catharos.societies.database.layout.tables.Societies.SOCIETIES.UUID);
		public static final org.jooq.UniqueKey<net.catharos.societies.database.layout.tables.records.SocietiesMembersRecord> KEY_SOCIETIES_MEMBERS_PRIMARY = createUniqueKey(net.catharos.societies.database.layout.tables.SocietiesMembers.SOCIETIES_MEMBERS, net.catharos.societies.database.layout.tables.SocietiesMembers.SOCIETIES_MEMBERS.SOCIETY, net.catharos.societies.database.layout.tables.SocietiesMembers.SOCIETIES_MEMBERS.MEMBER);
		public static final org.jooq.UniqueKey<net.catharos.societies.database.layout.tables.records.SocietiesRanksRecord> KEY_SOCIETIES_RANKS_PRIMARY = createUniqueKey(net.catharos.societies.database.layout.tables.SocietiesRanks.SOCIETIES_RANKS, net.catharos.societies.database.layout.tables.SocietiesRanks.SOCIETIES_RANKS.SOCIETY, net.catharos.societies.database.layout.tables.SocietiesRanks.SOCIETIES_RANKS.RANK);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<net.catharos.societies.database.layout.tables.records.MembersRanksRecord, net.catharos.societies.database.layout.tables.records.MembersRecord> FK_MEMBERS_HAS_RANKS_MEMBERS1 = createForeignKey(net.catharos.societies.database.layout.Keys.KEY_MEMBERS_PRIMARY, net.catharos.societies.database.layout.tables.MembersRanks.MEMBERS_RANKS, net.catharos.societies.database.layout.tables.MembersRanks.MEMBERS_RANKS.MEMBER);
		public static final org.jooq.ForeignKey<net.catharos.societies.database.layout.tables.records.MembersRanksRecord, net.catharos.societies.database.layout.tables.records.RanksRecord> FK_MEMBERS_HAS_RANKS_RANKS1 = createForeignKey(net.catharos.societies.database.layout.Keys.KEY_RANKS_PRIMARY, net.catharos.societies.database.layout.tables.MembersRanks.MEMBERS_RANKS, net.catharos.societies.database.layout.tables.MembersRanks.MEMBERS_RANKS.RANK);
		public static final org.jooq.ForeignKey<net.catharos.societies.database.layout.tables.records.RanksPermissionsRecord, net.catharos.societies.database.layout.tables.records.RanksRecord> FK_RANKS_HAS_PERMISSIONS_RANKS1 = createForeignKey(net.catharos.societies.database.layout.Keys.KEY_RANKS_PRIMARY, net.catharos.societies.database.layout.tables.RanksPermissions.RANKS_PERMISSIONS, net.catharos.societies.database.layout.tables.RanksPermissions.RANKS_PERMISSIONS.RANK);
		public static final org.jooq.ForeignKey<net.catharos.societies.database.layout.tables.records.RelationsRecord, net.catharos.societies.database.layout.tables.records.SocietiesRecord> FK_SOCIETIES_HAS_SOCIETIES_SOCIETIES1 = createForeignKey(net.catharos.societies.database.layout.Keys.KEY_SOCIETIES_PRIMARY, net.catharos.societies.database.layout.tables.Relations.RELATIONS, net.catharos.societies.database.layout.tables.Relations.RELATIONS.SOCIETY);
		public static final org.jooq.ForeignKey<net.catharos.societies.database.layout.tables.records.RelationsRecord, net.catharos.societies.database.layout.tables.records.SocietiesRecord> FK_SOCIETIES_HAS_SOCIETIES_SOCIETIES2 = createForeignKey(net.catharos.societies.database.layout.Keys.KEY_SOCIETIES_PRIMARY, net.catharos.societies.database.layout.tables.Relations.RELATIONS, net.catharos.societies.database.layout.tables.Relations.RELATIONS.SOCIETY2);
		public static final org.jooq.ForeignKey<net.catharos.societies.database.layout.tables.records.SocietiesMembersRecord, net.catharos.societies.database.layout.tables.records.SocietiesRecord> FK_SOCIETIES_HAS_MEMBERS_SOCIETIES = createForeignKey(net.catharos.societies.database.layout.Keys.KEY_SOCIETIES_PRIMARY, net.catharos.societies.database.layout.tables.SocietiesMembers.SOCIETIES_MEMBERS, net.catharos.societies.database.layout.tables.SocietiesMembers.SOCIETIES_MEMBERS.SOCIETY);
		public static final org.jooq.ForeignKey<net.catharos.societies.database.layout.tables.records.SocietiesMembersRecord, net.catharos.societies.database.layout.tables.records.MembersRecord> FK_SOCIETIES_HAS_MEMBERS_MEMBERS1 = createForeignKey(net.catharos.societies.database.layout.Keys.KEY_MEMBERS_PRIMARY, net.catharos.societies.database.layout.tables.SocietiesMembers.SOCIETIES_MEMBERS, net.catharos.societies.database.layout.tables.SocietiesMembers.SOCIETIES_MEMBERS.MEMBER);
		public static final org.jooq.ForeignKey<net.catharos.societies.database.layout.tables.records.SocietiesRanksRecord, net.catharos.societies.database.layout.tables.records.SocietiesRecord> FK_SOCIETIES_HAS_RANKS_SOCIETIES2 = createForeignKey(net.catharos.societies.database.layout.Keys.KEY_SOCIETIES_PRIMARY, net.catharos.societies.database.layout.tables.SocietiesRanks.SOCIETIES_RANKS, net.catharos.societies.database.layout.tables.SocietiesRanks.SOCIETIES_RANKS.SOCIETY);
		public static final org.jooq.ForeignKey<net.catharos.societies.database.layout.tables.records.SocietiesRanksRecord, net.catharos.societies.database.layout.tables.records.RanksRecord> FK_SOCIETIES_HAS_RANKS_RANKS2 = createForeignKey(net.catharos.societies.database.layout.Keys.KEY_RANKS_PRIMARY, net.catharos.societies.database.layout.tables.SocietiesRanks.SOCIETIES_RANKS, net.catharos.societies.database.layout.tables.SocietiesRanks.SOCIETIES_RANKS.RANK);
	}
}
