/**
 * This class is generated by jOOQ
 */
package net.catharos.societies.database.layout;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in societies
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table societies.members
	 */
	public static final net.catharos.societies.database.layout.tables.Members MEMBERS = net.catharos.societies.database.layout.tables.Members.MEMBERS;

	/**
	 * The table societies.members_ranks
	 */
	public static final net.catharos.societies.database.layout.tables.MembersRanks MEMBERS_RANKS = net.catharos.societies.database.layout.tables.MembersRanks.MEMBERS_RANKS;

	/**
	 * The table societies.ranks
	 */
	public static final net.catharos.societies.database.layout.tables.Ranks RANKS = net.catharos.societies.database.layout.tables.Ranks.RANKS;

	/**
	 * The table societies.ranks_settings
	 */
	public static final net.catharos.societies.database.layout.tables.RanksSettings RANKS_SETTINGS = net.catharos.societies.database.layout.tables.RanksSettings.RANKS_SETTINGS;

	/**
	 * The table societies.relations
	 */
	public static final net.catharos.societies.database.layout.tables.Relations RELATIONS = net.catharos.societies.database.layout.tables.Relations.RELATIONS;

	/**
	 * The table societies.societies
	 */
	public static final net.catharos.societies.database.layout.tables.Societies SOCIETIES = net.catharos.societies.database.layout.tables.Societies.SOCIETIES;

	/**
	 * The table societies.societies_ranks
	 */
	public static final net.catharos.societies.database.layout.tables.SocietiesRanks SOCIETIES_RANKS = net.catharos.societies.database.layout.tables.SocietiesRanks.SOCIETIES_RANKS;

	/**
	 * The table societies.societies_settings
	 */
	public static final net.catharos.societies.database.layout.tables.SocietiesSettings SOCIETIES_SETTINGS = net.catharos.societies.database.layout.tables.SocietiesSettings.SOCIETIES_SETTINGS;
}
